# Quiz 2 - Python and Pandas

This document wants to be a way to learn Jupyter notebook and review several Pandas concept that will be tested in quiz 2. 
I have built it myself, using the resources available on Canvas, and some additional resources.
I will be using some dataset available for free at [I will insert the link here]
If you guys notice any mistakes or want to contribute to this document, feel free to reach out to me.
This document is free and will be available under the [an open source license] 
The link to github is [link to the repository I will create]

## 0. Opening a dataset in Jupyter
This is the most basic operation to do, and to do so we need to import a library.

In [7]:
import pandas as pd # pd is just an alias, shorter and more easy to type (just two letters)

If you press `SHIFT + TAB` you can actually see the signature of the method, in case you forgot what parameter has to be passed

In [11]:
df = pd.read_excel(r"C:\Users\Aless\Desktop\Jupyter-and-Data-analysis\data\Airbnb.xlsx") # using r at the beginning means raw string

In this simple case, we just need to put the `PATH` inside the parenthesis. Notice how we assigned the return of the function to the variable `df` which stand for dataframe.

## 1. First look at a Dataframe
Now we can use the `df` variable to take a quick look at what the data look like

In [14]:
df.info() # quick breakdown of our data

<class 'pandas.DataFrame'>
RangeIndex: 291 entries, 0 to 290
Data columns (total 50 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        291 non-null    int64
 1   id                                291 non-null    int64
 2   last_scraped                      291 non-null    str
 3   host_id                           291 non-null    int64
 4   host_url                          291 non-null    str
 5   host_name                         291 non-null    str
 6   host_since                        291 non-null    str
 7   host_response_time                209 non-null    str
 8   host_response_rate                209 non-null    float64
 9   host_is_superhost                 291 non-null    str
 10  host_listings_count               291 non-null    int64
 11  street                            291 non-null    str
 12  zipcode                           290 non-null    float64
 13  property_type                     291 non-null    str
 14  room_type                         291 non-null    str
 15  accommodates                      291 non-null    int64
 16  bathrooms                         285 non-null    float64
 17  bedrooms                          291 non-null    int64
 18  beds                              291 non-null    int64
 19  bed_type                          291 non-null    str
 20  price                             291 non-null    int64
 21  weekly_price                      161 non-null    float64
 22  monthly_price                     125 non-null    float64
 23  security_deposit                  221 non-null    float64
 24  cleaning_fee                      241 non-null    float64
 25  guests_included                   291 non-null    int64
 26  extra_people                      291 non-null    int64
 27  minimum_nights                    291 non-null    int64
 28  maximum_nights                    291 non-null    int64
 29  availability_30                   291 non-null    int64
 30  availability_60                   291 non-null    int64
 31  availability_90                   291 non-null    int64
 32  availability_365                  291 non-null    int64
 33  number_of_reviews                 291 non-null    int64
 34  first_review                      274 non-null    datetime64[us]
 35  last_review                       274 non-null    datetime64[us]
 36  review_scores_rating              274 non-null    float64
 37  review_scores_accuracy            271 non-null    float64
 38  review_scores_cleanliness         271 non-null    float64
 39  review_scores_checkin             271 non-null    float64
 40  review_scores_communication       271 non-null    float64
 41  review_scores_location            271 non-null    float64
 42  review_scores_value               271 non-null    float64
 43  instant_bookable                  291 non-null    str
 44  cancellation_policy               291 non-null    str
 45  require_guest_phone_verification  291 non-null    str
 46  reviews_per_month                 274 non-null    float64
 47  maximum_stay                      291 non-null    str
 48  host_since_date                   291 non-null    datetime64[us]
 49  last_scraped_date                 291 non-null    datetime64[us]
dtypes: datetime64[us](4), float64(15), int64(17), str(14)
memory usage: 113.8 KB

In [15]:
df.shape # tell us the rows and colums

(291, 50)

In [18]:
df.head() # tell us the first

,Unnamed: 0,id,last_scraped,host_id,host_url,host_name,host_since,host_response_time,host_response_rate,host_is_superhost,...,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,require_guest_phone_verification,reviews_per_month,maximum_stay,host_since_date,last_scraped_date
0,0,11156,06/11/2019,40855,https://www.airbnb.com/users/show/40855,Colleen,23/09/2009,within a day,1.0,f,...,10.0,10.0,10.0,f,moderate,f,1.53,2 to 12 months,2009-09-23,2019-11-06
1,3,14250,06/11/2019,55948,https://www.airbnb.com/users/show/55948,Heidi,20/11/2009,within a few hours,1.0,f,...,8.0,9.0,8.0,f,strict_14_with_grace_period,f,0.04,Less than a month,2009-11-20,2019-11-06
2,4,15253,05/11/2019,59850,https://www.airbnb.com/users/show/59850,Morag,03/12/2009,within an hour,1.0,f,...,10.0,10.0,9.0,t,strict_14_with_grace_period,f,3.63,Less than a month,2009-12-03,2019-11-05
3,5,20865,06/11/2019,64282,https://www.airbnb.com/users/show/64282,Fiona,19/12/2009,within a day,1.0,t,...,10.0,10.0,9.0,f,strict_14_with_grace_period,t,0.17,1 to 3 years,2009-12-19,2019-11-06
4,6,44545,05/11/2019,112237,https://www.airbnb.com/users/show/112237,Atari,22/04/2010,within an hour,1.0,t,...,10.0,10.0,10.0,f,strict_14_with_grace_period,t,0.65,1 to 3 years,2010-04-22,2019-11-05

In [19]:
df.tail() # tell us the last 5

,Unnamed: 0,id,last_scraped,host_id,host_url,host_name,host_since,host_response_time,host_response_rate,host_is_superhost,...,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,require_guest_phone_verification,reviews_per_month,maximum_stay,host_since_date,last_scraped_date
286,299,771702,05/11/2019,3564414,https://www.airbnb.com/users/show/3564414,Paris,14/09/2012,within an hour,1.0,f,...,10.0,10.0,9.0,f,flexible,t,0.47,3 years +,2012-09-14,2019-11-05
287,300,771920,05/11/2019,2594223,https://www.airbnb.com/users/show/2594223,Danielle,10/06/2012,NaN,NaN,f,...,10.0,10.0,10.0,f,moderate,f,0.14,Less than a month,2012-06-10,2019-11-05
288,301,773492,06/11/2019,4072802,https://www.airbnb.com/users/show/4072802,Summer,06/11/2012,within an hour,1.0,t,...,10.0,9.0,10.0,f,strict_14_with_grace_period,f,0.38,2 to 12 months,2012-11-06,2019-11-06
289,302,775101,05/11/2019,4088777,https://www.airbnb.com/users/show/4088777,Holland,07/11/2012,NaN,NaN,f,...,10.0,10.0,9.0,f,strict_14_with_grace_period,f,0.42,3 years +,2012-11-07,2019-11-05
290,303,775552,06/11/2019,2650727,https://www.airbnb.com/users/show/2650727,Robbie,16/06/2012,within an hour,1.0,f,...,10.0,10.0,9.0,t,strict_14_with_grace_period,f,1.87,3 years +,2012-06-16,2019-11-06

Let's take now a look at a sample question of the *Practice Quiz*.

```How many variables contain missing values?```

To answer this question we can use the

In [29]:
df.isnull() # this return a new dataframe with true = 1 and  false = 0, but it's not very useful now...

,Unnamed: 0,id,last_scraped,host_id,host_url,host_name,host_since,host_response_time,host_response_rate,host_is_superhost,...,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,require_guest_phone_verification,reviews_per_month,maximum_stay,host_since_date,last_scraped_date
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
287,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
288,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
289,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
290,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [30]:
df.isnull().sum() # This will sum the value of each column, for example for id we get 0 since there is not missing value

Unnamed: 0                            0
id                                    0
last_scraped                          0
host_id                               0
host_url                              0
host_name                             0
host_since                            0
host_response_time                   82
host_response_rate                   82
host_is_superhost                     0
host_listings_count                   0
street                                0
zipcode                               1
property_type                         0
room_type                             0
accommodates                          0
bathrooms                             6
bedrooms                              0
beds                                  0
bed_type                              0
price                                 0
weekly_price                        130
monthly_price                       166
security_deposit                     70
cleaning_fee                         50
guests_included                       0
extra_people                          0
minimum_nights                        0
maximum_nights                        0
availability_30                       0
availability_60                       0
availability_90                       0
availability_365                      0
number_of_reviews                     0
first_review                         17
last_review                          17
review_scores_rating                 17
review_scores_accuracy               20
review_scores_cleanliness            20
review_scores_checkin                20
review_scores_communication          20
review_scores_location               20
review_scores_value                  20
instant_bookable                      0
cancellation_policy                   0
require_guest_phone_verification      0
reviews_per_month                    17
maximum_stay                          0
host_since_date                       0
last_scraped_date                     0
dtype: int64

In [34]:
missing_counts = df.isnull().sum() 
missing_counts[missing_counts > 0] # we can use the square brackets to filter only when it's true

host_response_time              82
host_response_rate              82
zipcode                          1
bathrooms                        6
weekly_price                   130
monthly_price                  166
security_deposit                70
cleaning_fee                    50
first_review                    17
last_review                     17
review_scores_rating            17
review_scores_accuracy          20
review_scores_cleanliness       20
review_scores_checkin           20
review_scores_communication     20
review_scores_location          20
review_scores_value             20
reviews_per_month               17
dtype: int64

In [33]:
len(missing_counts[missing_counts > 0]) # the final answer

NameError: name 'missing_counts' is not defined

## 2. Data types

## 3. Summary statistics

## 4. Missing values

## 5. Unit of analysis

## 6. Grouping and aggregation

## 7. Filtering and selecting

## 8. Categorical variables

## 9. Date and time variables

## 10. Creating new columns

## 11. Sorting

## 12. Visualization with Seaborn

## 13. Interpreting results